// defines that are generated by app framework.
// Forward declarations to avoid warnings in scripted tests (usually found in
// the callback header file, that also generated by app framework).

#define EMBER_AF_PLUGIN_RF4CE_MSO_KEY_REPEAT_INTERVAL_MS                  120
#define EMBER_AF_PLUGIN_RF4CE_MSO_MAX_USER_CONTROL_RECORDS                1
#define EMBER_AF_PLUGIN_RF4CE_MSO_RESPONSE_WAIT_TIME_MS                   100
#define EMBER_AF_PLUGIN_RF4CE_MSO_AUTO_CHECK_VALIDATION_PERIOD_MS         500
#define EMBER_AF_PLUGIN_RF4CE_MSO_LINK_LOST_WAIT_TIME_MS                  10000
#define EMBER_AF_PLUGIN_RF4CE_MSO_MAX_PAIRING_CANDIDATES                  3
#define EMBER_AF_PLUGIN_RF4CE_MSO_KEY_EXCHANGE_TRANSFER_COUNT             4
#define EMBER_AF_PLUGIN_RF4CE_PROFILE_VENDOR_ID                           0xABCD
#define EMBER_AF_PLUGIN_RF4CE_MSO_PERIPHERAL_ID_ENTRIES                   2
#define EMBER_AF_PLUGIN_RF4CE_MSO_GENERAL_PURPOSE_ENTRIES                 1

void emberAfPluginRf4ceMsoBindingCompleteCallback(EmberAfRf4ceMsoBindingStatus status,
                                                  int8u pairingIndex);

void emberAfPluginRf4ceMsoStartValidationCallback(int8u pairingIndex);

void emberAfPluginRf4ceMsoUserControlCallback(const EmberAfRf4ceMsoUserControlRecord *record);

EmberAfRf4ceStatus emberAfPluginRf4ceMsoGetIrRfDatabaseAttributeCallback(int8u pairingIndex,
                                                                         int8u entryIndex,
                                                                         int8u *valueLength,
                                                                         int8u *value);

boolean emberAfPluginRf4ceMsoHaveIrRfDatabaseAttributeCallback(int8u pairingIndex,
                                                               int8u entryIndex);

void emberAfPluginRf4ceMsoIncomingIrRfDatabaseAttributeCallback(int8u pairingIndex,
                                                                int8u entryIndex,
                                                                int8u valueLength,
                                                                const int8u *value);
EmberStatus emberAfPluginRf4ceMsoGetIrRfDatabaseEntryCallback(EmberAfRf4ceMsoKeyCode keyCode,
                                                              EmberAfRf4ceMsoIrRfDatabaseEntry *entry);
