
void emberAfPluginDeviceQueryServiceEnableDisable(boolean enable);
boolean emberAfPluginDeviceQueryServiceGetEnabledState(void);
void emberAfPluginDeviceQueryServiceGetCurrentDiscoveryTargetEui64(EmberEUI64 returnEui64);
