WORKSPACE=../../..
-include $(WORKSPACE)/prj/def.mk

MOD_SRC_EXTRA_DIRS+=
MOD_INC_EXTRA_DIR+=
MOD_DLL_DEP_MOD+=

UT_INC_EXTRA_DIR+=
UT_SRC_MOCK_FILENAMES+=
UT_SRC_EXTRA_DIRS+=

UT_LIBDIR_EXTRA+=$(MINGW_HOME)/lib
ifeq ($(ARCH_OS), X86_WINDOWS)
UT_LIB_EXTERNAL+=
endif
UT_LIB_DEP_MOD+=

IT_INC_EXTRA_DIR+=
IT_SRC_MOCK_FILENAMES+=
IT_SRC_EXTRA_DIRS+=

IT_LIBDIR_EXTRA+=$(MINGW_HOME)/lib
IT_LIB_EXTERNAL+=
IT_LIB_DEP_MOD+=gsp


-include $(WORKSPACE)/prj/dep.mk


